<h1>NUMPY PROGRAMS</h1>

<H3>CREATING NUMPY</H3>

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [14]:
b=np.array([[1,2,3],[4,5,6]])
print(b) 

[[1 2 3]
 [4 5 6]]


In [31]:
c=np.array([[[1,2],[3,4],[5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [5]:
e=np.array([1,2,3],dtype=str)
d=np.array([1,2,3],dtype=float)
print(e)
print(d)

['1' '2' '3']
[1. 2. 3.]


In [10]:
np.arange(1,11,1).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.random.random((3,4))

array([[0.8029546 , 0.05426577, 0.34826446, 0.56132297],
       [0.62235178, 0.14903778, 0.01447662, 0.066523  ],
       [0.93192623, 0.38251758, 0.33388632, 0.29769991]])

In [18]:
np.linspace(12,13,5)
# The total range is:
# 13−12=1
# There are 
# 5−1=4 intervals because there are 5 points.
# The interval size (step size) is:
# Step size=Range/Number of intervals=1/4=0.25
# Result:
# The function generates 5 evenly spaced points between 12 and 13. These are:
# [12.0,12.25,12.5,12.75,13.0]
# Starting at 12.0, each subsequent value increases by 0.25
# 0.25:
# 12.0+0.25=12.25
# 12.5+0.25=12.75
# 12.75+0.25=13.0 (stop value)



array([12.  , 12.25, 12.5 , 12.75, 13.  ])

In [19]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.arange(12).reshape(6,2,1)

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]]])

In [28]:
a.ndim

1

In [32]:
c.ndim

3

In [36]:
print(c.shape)
print(c)

(1, 3, 2)
[[[1 2]
  [3 4]
  [5 6]]]


In [38]:
a.shape #3
a

array([1, 2, 3])

In [39]:
c.size

6

<h3>Array Operations</h3>

In [3]:
import numpy as np
a=np.arange(0,12).reshape(3,4)
a1=np.arange(13,25).reshape(2,3,2)

In [49]:
a>7

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [50]:
a+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [51]:
a1+a

ValueError: operands could not be broadcast together with shapes (2,3,2) (3,4) 

In [63]:
a1=np.arange(13,25).reshape(3,4)
c=(a1+a).reshape(2,3,2)
print(c)

print(c[0,1,1])
print(c[1,0,0])

[[[13 15]
  [17 19]
  [21 23]]

 [[25 27]
  [29 31]
  [33 35]]]
19
25


In [5]:
import numpy as py
py.random.randint(1,10,60).reshape(2,3,10)

array([[[7, 3, 6, 1, 7, 2, 4, 8, 6, 3],
        [1, 5, 9, 1, 6, 9, 2, 1, 6, 4],
        [3, 8, 1, 4, 6, 5, 5, 9, 2, 5]],

       [[9, 1, 2, 6, 1, 1, 2, 5, 3, 9],
        [3, 5, 7, 9, 8, 3, 1, 7, 9, 8],
        [8, 8, 4, 4, 7, 6, 5, 2, 9, 5]]], dtype=int32)

In [10]:
matrix=np.arange(1,19,1).reshape(3,2,3) #rows columns elements
print(matrix)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [12]:
matrix2=np.arange(1,19,1).reshape(1,2,9)
print(matrix2)

[[[ 1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18]]]


In [13]:
import numpy as np
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m1)
print(m1.diagonal())
print(m1.flatten())
print(m1.min())
print(m1.max())
print(m1.mean())
print(m1.sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[1 2 3 4 5 6 7 8 9]
1
9
5.0
45


In [14]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m2=np.array([[10,11,12],[13,14,15],[16,17,18]])
print(m1)
print(m2)
print(np.hstack((m1,m2)))
print(20*'*')
print(np.vstack((m1,m2)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
********************
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
